resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource 
    tag: latest

resources:
  - name: terraform
    type: terraform
    source:
      env_name: staging
      vars:
        tag_name: concourse
      env:
        AWS_ACCESS_KEY_ID: {{environment_access_key}}
        AWS_SECRET_ACCESS_KEY: {{environment_secret_key}}

jobs:
- name: terraform-plan
  plan:
  - get: project-git-repo
  - put: terraform
    params:
      env_name: staging
      terraform_source: project-git-repo/terraform
      plan_only: true
      vars:
        subnet_cidr: 10.0.1.0/24